### PR TITLE
adjust metabaloci cost naming

### PR DESCRIPTION
**Pull request by aremazeilles**
**DO NOT merge** 

If the change sounds like correct to you, I will push it to the origin repository, and then bring it to here.

So I basically changed the filename to be  `subject_01_cond_01_choice_metabolicCost.yaml` instead of `subject_01_choice_metabolicCost.yaml` . 

This would be the needed adjustment, right?

### CODE REVIEW

**Comment by alfonsotecnalia** [comment]
It should be subject_01_**_condition_**_01_choice_metabolicCost.yaml

**Comment by aremazeilles** [comment]
hum, right, it is a definition file, so full name. ..
now better?

**Comment by alfonsotecnalia** [comment]
Now it is ok

**Comment by aremazeilles** [comment]
ok. Requesting to Jawad the push to the origin repsitory

**Comment by alfonsotecnalia** [comment]
Ok. When done, let me know and I will change entry point and docker image in the .yaml and upload to the website.

**Comment by aremazeilles** [comment]
Already merged to master

**Pull request closed without merging**
